### ISSUE TITLE
DistributionNotFound when running jitter

### ISSUE THREAD

**Issue by marmor7** [EverythingMe/jitter#1]
Getting the following stack trace when trying to run jitter:

> Traceback (most recent call last):
>   File "/usr/local/bin/jitter", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
>     working_set.require(**requires**)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
>     raise DistributionNotFound(req)  # XXX put more info here
> pkg_resources.DistributionNotFound: nose

I have nose installed, as `pip list` shows:

> nose (1.3.7)

Notes: 
1. I had to install jitter via sudo, there were issues creating folders without sudo
2. Mac running OS X 10.9.5

**Comment by akariv** [comment]
I've seen issues like this happen when you have installed a different version of python besides the default that comes with OS X (e.g. via HomeBrew etc.)

You might have nose installed for one installation but not the other.

I suggest you try to reinstall nose via `sudo pip install nose` and see what happens.
